# Generated by Django 2.1.4 on 2019-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_windows_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('host_ip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='windows_software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows_software_name', models.CharField(max_length=200)),
                ('windows_software_location', models.FileField(upload_to='windows_software/')),
            ],
        ),
    ]
